source "http://rubygems.org"
gem 'cinch', :git => "https://github.com/injekt/cinch.git", :branch => "develop"
gem 'chronic'
gem 'ago'
gem 'mongo_mapper', '~>0.8'
gem 'nokogiri'
gem 'httparty'
gem 'mechanize'
gem 'rae'
gem 'imdb'
gem 'ideone'
gem 'shoulda'
gem 'jeweler'
gem 'i18n'
gem 'tzinfo'
