source "http://rubygems.org"
gem 'cinch', '~>1.0'
gem 'chronic'
gem 'ago'
gem 'mongo_mapper', '~>0.8'
gem 'nokogiri'
gem 'httparty'
gem 'mechanize'
gem 'rae'
gem 'imdb'
gem 'ideone'
gem 'shoulda'
gem 'jeweler'
